MCU   = STM32F411
BOARD = BLACKPILL_STM32_F411

SPLIT_KEYBOARD   = no
EEPROM_DRIVER    = vendor

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE  = yes
EXTRAKEY_ENABLE  = yes
CONSOLE_ENABLE   = yes
COMMAND_ENABLE   = yes
NKRO_ENABLE      = yes
UNICODE_ENABLE   = no
BLUETOOTH_ENABLE = no

KEYBOARD_SHARED_EP = yes
