MCU   = STM32F401
BOARD = BLACKPILL_STM32_F401

SPLIT_KEYBOARD   = yes
EEPROM_DRIVER    = vendor
SERIAL_DRIVER    = usart

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE  = yes
EXTRAKEY_ENABLE  = yes
CONSOLE_ENABLE   = yes
COMMAND_ENABLE   = yes
NKRO_ENABLE      = yes
UNICODE_ENABLE   = no
BLUETOOTH_ENABLE = no

KEYBOARD_SHARED_EP = yes
